version: '3.1'
services:
  db:
    image: "mysql:5.7.30"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db-data:/var/lib/mysql
  www:
    image: "civicrm-wp-docker:5.25.0"
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
volumes:
  db-data: